<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cs625_full_system</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="1933825889@qq.com">yff</maintainer>
  <license>TODO: License declaration</license>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>eli_cs_robot_driver</depend>
  <depend>eli_cs_robot_description</depend>
  <depend>elite_cs625_moveit_config</depend>
  <depend>cs625_kinematics</depend>
  <depend>tcp_bridge</depend>
  <depend>environment_point_cloud_publisher</depend>
  <depend>workspace_pointcloud_sampler</depend>
  <depend>environment_collision_generator</depend>
  <depend>cs625_trajectory_tools</depend>
  <depend>cs625_state_monitor</depend>
  <depend>cs625_task_manager</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
